# working with json.

In [5]:
import pandas as pd

In [7]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [9]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.0414
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.7680
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.9300
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,4.3200
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,1.1500
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,2.7000
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.1940
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.2700
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-02,1759363202,0.3010

# Now let's work with SQL

In [12]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 8.5 MB/s eta 0:00:02
     --- ------------------------------------ 1.0/11.9 MB 2.6 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/11.9 MB 2.4 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 1.8 MB/s eta 0:00:06
     ------ --------------------------------- 1.8/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 1.6 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 1.6 MB/s eta 0:00:07
     ------- -------------------------------- 2.4/11.9 MB 1.6 MB/s eta 0:00:07
     --------- ------------------------------ 2.9/11.9 MB 1.5 MB/s eta 0:00:07
     --------- ------------------------------ 2.9/11.9 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.1/11.9 MB 1.4 MB/s eta 0:00:07
     ----------- ---------------------------- 3.4/11.9 MB 1.4 MB/s eta 0:00:07
     ------------ --------------------------- 3.7/11.9 MB 1.3 MB/s eta 0:00:07
     ------------ --------------------------- 3.7/11.9 MB 1.3 MB/s eta 0:00:07
     ------------- -------------------------- 3.9/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.2/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.2/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.5/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.5/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.7/11.9 MB 1.1 MB/s eta 0:00:07
     ---------------- ----------------------- 5.0/11.9 MB 1.1 MB/s eta 0:00:07
     ----------------- ---------------------- 5.2/11.9 MB 1.1 MB/s eta 0:00:07
     ------------------ --------------------- 5.5/11.9 MB 1.1 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.1 MB/s eta 0:00:06
     -------------------- ------------------- 6.0/11.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.3/11.9 MB 1.1 MB/s eta 0:00:05
     ----------------------- ---------------- 6.8/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.1 MB/s eta 0:00:04
     ---------------------------- ----------- 8.4/11.9 MB 1.1 MB/s eta 0:00:04
     ----------------------------- ---------- 8.7/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.2 MB/s eta 0:00:03
     -------------------------------- ------- 9.7/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.2 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247959 sha256=46c2e002b94e67edc56d91e8df99c267838998922164191f64c568f239f80a8d
  Stored in directory: c:\users\sshau\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [33]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\sshau\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: mysql-connector-python in c:\users\sshau\anaconda3\lib\site-packages (9.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sshau\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sshau\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [43]:
import mysql.connector 
from sqlalchemy import create_engine

In [45]:
engine = create_engine("mysql+mysqlconnector://root:@localhost/world")

In [37]:
# conn = mysql.connector.connect(host='localhost', user = 'root', password = '', database = 'world')

In [47]:
df = pd.read_sql_query("SELECT * FROM countrylanguage", engine)

In [49]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]